#assigment o.p.
x=34
print(x)

#urnary minus
a=7
print(-a)

#relational
p=10
q=5
print(p>q)
print(p==q)

#logical
x=True
y=False
print(x and y)
print(x or y)
print(not x)

#boolean
is_pass=True
print(is_pass)

#bitwise
a=5
b=3
print(a&b)
print(a|b)

#membership
numbers=[1,2,3,4,6]
print(2 in numbers)
print(5 not in numbers)

#identity
x=10
y=10
print(x is y)
print(x is not y)

a=56
b=78
print(b-a)